identifier: de.airsi.listenbrainz-plus
name: ListenBrainz Plus
description: Scrobble plays from Cider to ListenBrainz.
author: airsi
repo: https://github.com/airsi/cider-listenbrainz-plus-plugin
entry:
  "plugin.js":
    type: main